#---------------------------------------------------------------------------------
# Environment Validation & Setup)
#---------------------------------------------------------------------------------
.SUFFIXES:

ifeq ($(strip $(DEVKITPPC)),)
$(error "Please set DEVKITPPC in your environment. export DEVKITPPC=<path to>devkitPPC")
endif

include $(DEVKITPPC)/wii_rules

#---------------------------------------------------------------------------------
# TARGET is the name of the output
# BUILD is the directory where object files & intermediate files will be placed
# SOURCES is a list of directories containing source code
# INCLUDES is a list of directories containing extra header files
#---------------------------------------------------------------------------------
TARGET      := boot
BUILD       := build
INCLUDES    := ../
DATA        := 

#--- Core Sources ---
SOURCES     := ../
SOURCES     += ../cl/
SOURCES     += ../config/
SOURCES     += ../debug_mem.o
SOURCES     += ../profiler/
SOURCES     += ../serial_ipc/

#--- Dreamcast Emulation Core ---
SOURCES     += ../dc/
SOURCES     += ../dc/aica/
SOURCES     += ../dc/asic/
SOURCES     += ../dc/gdrom/
SOURCES     += ../dc/maple/
SOURCES     += ../dc/mem/
SOURCES     += ../dc/pvr/
SOURCES     += ../dc/sh4/
SOURCES     += ../dc/sh4/rec_v2/

#--- Plugins & Internal Modules ---
SOURCES     += ../plugins/
SOURCES     += ../plugs/nullExtDev/
SOURCES     += ../plugs/drkMapleDevices/
SOURCES     += ../plugs/EmptyAICA/
SOURCES     += ../plugs/ImgReader/
SOURCES     += ../plugs/gui/
SOURCES     += ../plugs/drkPvr/

#--- Wii Specific & GUI ---
SOURCES     += ../wii/
SOURCES     += ../wii/dc/sh4/rec_v2/
SOURCES     += ../gui/

#---------------------------------------------------------------------------------
# Compilation Flags (CFLAGS)
#---------------------------------------------------------------------------------

# Base Flags
CFLAGS  := -save-temps -g -O2 -Wall
CFLAGS  += $(MACHDEP) $(INCLUDE)
CFLAGS  += -D_WII -DRELEASE

# Optimization & Code Gen
CFLAGS  += -frename-registers
CFLAGS  += -fno-strict-aliasing
CFLAGS  += -fsingle-precision-constant
CFLAGS  += -fomit-frame-pointer
CFLAGS  += -ffast-math

# C++ Specific Flags
CXXFLAGS := $(CFLAGS)
CXXFLAGS += -fno-exceptions
CXXFLAGS += -fno-rtti
CXXFLAGS += -g -O0  # for debugging on dolphin using addr2line

# Linker Flags
LDFLAGS  := -g $(MACHDEP) -Wl,-Map,$(TARGET).map

# Enable link-time optimization for cross-module inlining (pvrLock optimization)
# (compilation didnt worked but keeping for now for info)
# CFLAGS += -flto
# LDFLAGS += -flto
# Optional: More aggressive optimization
# CFLAGS += -O3 -fomit-frame-pointer
#---------------------------------------------------------------------------------
# Libraries
#---------------------------------------------------------------------------------
LIBS    := -lwiiuse -lbte -lfat -logc -lm

#---------------------------------------------------------------------------------
# list of directories containing libraries, this must be the top level containing
# include and lib
#---------------------------------------------------------------------------------
LIBDIRS	:=

# Build Logic (Avoid editing below this line)
#---------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))

export OUTPUT   := $(CURDIR)/$(TARGET)
export VPATH    := $(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
                   $(foreach dir,$(DATA),$(CURDIR)/$(dir))
export DEPSDIR  := $(CURDIR)/$(BUILD)

#---------------------------------------------------------------------------------
# automatically build a list of object files for our project
#---------------------------------------------------------------------------------
CFILES      := $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES    := $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
sFILES      := $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
SFILES      := $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.S)))
BINFILES    := $(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))

#---------------------------------------------------------------------------------
# use CXX for linking C++ projects, CC for standard C
#---------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
    export LD := $(CC)
else
    export LD := $(CXX)
endif

export OFILES   := $(addsuffix .o,$(BINFILES)) \
                   $(CPPFILES:.cpp=.o) $(CFILES:.c=.o) \
                   $(sFILES:.s=.o) $(SFILES:.S=.o)

#---------------------------------------------------------------------------------
# build a list of include paths
#---------------------------------------------------------------------------------
export INCLUDE  := $(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
                   $(foreach dir,$(LIBDIRS),-I$(dir)/include) \
                   -I$(CURDIR)/$(BUILD) \
                   -I$(LIBOGC_INC)

#---------------------------------------------------------------------------------
# build a list of library paths
#---------------------------------------------------------------------------------
export LIBPATHS := $(foreach dir,$(LIBDIRS),-L$(dir)/lib) \
                   -L$(LIBOGC_LIB)

.PHONY: $(BUILD) clean run

#---------------------------------------------------------------------------------
$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile

#---------------------------------------------------------------------------------
clean:
	@echo cleaning ...
	@rm -fr $(BUILD) $(OUTPUT).elf $(OUTPUT).dol $(OFILES)
#---------------------------------------------------------------------------------
run:
	wiiload $(OUTPUT).dol

#---------------------------------------------------------------------------------
else

DEPENDS := $(OFILES:.o=.d)

#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
$(OUTPUT).dol: $(OUTPUT).elf
$(OUTPUT).elf: $(OFILES)

-include $(DEPENDS)

#---------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------
